# -*- coding: utf-8 -*-
"""Ex10Modulo(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17dCTfPldUeaZCFLkAgROId5zvtRgOcTl
"""

def ledadosprodutos():
    descricao=input("Digite a descrição do produto:")
    quant=int(input("Digite a quantidade do produto:"))
    preccompra=float(input("Digite o preço de compra:"))
    precvenda=float(input("Digite o preço de venda:"))
    
    produto={"descricao":descricao,"quant":quant,"preccompra":preccompra,"precvenda":precvenda}
    
    return produto

def procuraproduto(listadeprodutos,produto):
  pos=-1
  for i in range(len(listadeprodutos)):
    prod=listadeprodutos[i]
    if prod["descricao"]==produto["descricao"]:
      pos=i
      return pos
  
  return pos

def mostradadosprodutos(listadeprodutos):
    for p in listadeprodutos:
        print(p)
        #print("Nome=",p["nome"]," Endereço=",p["endereco"]," Salário=",p["salario"])
        
def ordenadescricao(e):
    return e["descricao"]
def calcquanttot(listadeprodutos):
  qt=0
  for p in listadeprodutos:
    qt=qt+p["quant"]
  return qt

def buscamaiormenor(listadeprodutos):
  for i in range(len(listadeprodutos)):
    prod=listadeprodutos[i]
    if i==0:
      maior=menor=prod["precvenda"]
      descrmaior=descrmenor=prod["descricao"]

    if prod["precvenda"] > maior:
      maior=prod["precvenda"]
      descrmaior=prod["descricao"]

    if prod["precvenda"] < menor:
      menor=prod["precvenda"]
      descrmenor=prod["descricao"]

  return descrmaior,descrmenor