# -*- coding: utf-8 -*-
"""moduloq01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWBztFJrb8VtIWJSkzCx0ZewBJkjqV3h
"""

class pais:
  __codigo = str()
  __nome = str()
  __populacao = int()
  __dimensao = float()
  __lista_fronteira = []

  def setcodigo(self, codigo):
    self.__codigo = codigo
    
  def setnome(self, nome):
    self.__nome = nome

  def setpopulacao(self, populacao):
    self.__populacao = populacao

  def setdimensao(self, dimensao):
    self.__dimensao = dimensao

  def setfronteira(self, lista_fronteira):
    self.__lista_fronteira = lista_fronteira

  def getcodigo(self):
    return self.__codigo
    
  def getnome(self):
    return self.__nome

  def getpopulacao(self):
    return self.__populacao

  def getdimensao(self):
    return self.__dimensao
  
  def getfronteira(self):
    return self.__lista_fronteira
  
  def densidade(self):
    densidadeP = self.__populacao/self.__dimensao
    return densidadeP

  def verifica_vizinho(self, pais):
    aux = pais.getfronteira
    lista_vizinhos = []
    for i in self.__lista_fronteira:
      for j in pais.getfronteira():
        if i == j:
          lista_vizinhos.append(i)
    print(lista_vizinhos)

  def verifica_pais(self, pais1):
    if self.__codigo == pais1.getcodigo():
      print("Pais já existe")

  def verifica_fronteira(self, pais1):
    for i in self.__lista_fronteira:
      if i == pais1.getnome().lower():
        print("Os paises fazem fronteira!")
        return 0
    print('Os paises não fazem fronteira!')