# -*- coding: utf-8 -*-
"""moduloQuadrado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-ixY5uJ7EbjsQcEkMlOLD8--flVf5Gu
"""

class quadrado:
  tamLado=0
  def __init__(self, tamLado=None):
    if tamLado is None:
      self.tamLado=0
    else:
      self.tamLado = tamLado
  def retVal(self):
    print("Lado do quadrado: {}".format(self.tamLado))
  def mudarVal(self):
    self.tamLado = float(input('Digite o tamanho para o lado: '))
  def calcArea(self):
    return (self.tamLado**2)