# -*- coding: utf-8 -*-
"""moduloq03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pX51SD_KcUsD-DOSGl3Q2c2pDa2Flekt
"""

class continente:
  nome_continente = str()
  pais = {'nome': [], 'populacao': [], 'dimensao': []}

  def __init__(self, nome):
    self.nome_continente = nome

  def add_pais(self, nome, populacao, dimensao):
    self.pais['nome'].append(nome)
    self.pais['populacao'].append(populacao)
    self.pais['dimensao'].append(dimensao)

  def dimensao_continente(self):
    dimensao_continente = 0.0
    aux = self.pais['dimensao']
    for i in aux:
      dimensao_continente += i
    return dimensao_continente
  
  def populacao_total(self):
    populacao_continente = 0
    aux = self.pais['populacao']
    for i in aux:
      populacao_continente += i
    return populacao_continente
  
  def menor_populacao(self):
    aux = self.pais['populacao']
    aux_nome = self.pais['nome']
    populacao_menor = aux[0]
    pais_menor = int()
    for i in aux:
      if i<populacao_menor:
        populacao_menor = i
        pais_menor = aux.index(i)
    
    nome_menor_pais = aux_nome[pais_menor]
    return nome_menor_pais

  def maior_populacao(self):
    aux = self.pais['populacao']
    aux_nome = self.pais['nome']
    populacao_maior = aux[0]
    pais_maior = int()
    for i in aux:
      if i>populacao_maior:
        pais_maior = aux.index(i)
    
    nome_maior_pais = aux_nome[pais_maior]
    return nome_maior_pais
  
  def menor_territorio(self):
    aux = self.pais['dimensao']
    aux_nome = self.pais['nome']
    territorio_menor = aux[0]
    pais_menor = int()
    for i in aux:
      if i<territorio_menor:
        pais_menor = aux.index(i)
    
    nome_menor_pais = aux_nome[pais_menor]
    return nome_menor_pais

  def maior_territorio(self):
    aux = self.pais['dimensao']
    aux_nome = self.pais['nome']
    territorio_maior = aux[0]
    pais_maior = int()
    for i in aux:
      if i>territorio_maior:
        pais_maior = aux.index(i)
    
    nome_maior_pais = aux_nome[pais_maior]
    return nome_maior_pais  

  def razao_menor_maior(self):
    aux = self.pais['dimensao']
    aux_nome = self.pais['nome']
    territorio_maior = aux[0]
    territorio_menor = aux[0]
    pais_maior = int()
    pais_menor = int()
    for i in aux:
      if i>territorio_maior:
        pais_maior = i
      if i<territorio_menor:
        pais_menor = i

      razao = pais_maior-pais_menor
    return razao
    
  def imprime_continente(self):
    print('nome continente: {}, paises: {}'.format(self.nome_continente, self.pais))